# ==============================================================================
# SCRIPT: 03_Run_GSEA.R
# PURPOSE: Gene Set Enrichment Analysis (GO:BP) and Network Visualization
# ==============================================================================
library(dplyr)
library(ggplot2)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)

message("\n>>> Running GSEA for: ", COMPARISON_PREFIX)

# 1. Load the Ranked List generated by Script 02
if(!file.exists(DEG_CSV_FILE)) {
  stop(">>> ERROR: Cannot find the DGE CSV. Make sure Script 02 ran successfully!")
}
deg_data <- read.csv(DEG_CSV_FILE)

# 2. Format the Ranked Vector strictly for clusterProfiler
ranked_genes <- deg_data$avg_log2FC
names(ranked_genes) <- deg_data$gene
ranked_genes <- na.omit(ranked_genes)
ranked_genes <- ranked_genes[!duplicated(names(ranked_genes))]
ranked_genes <- sort(ranked_genes, decreasing = TRUE)

# 3. Fetch GO:BP Pathways
message(">>> Fetching GO:BP database...")
m_t2g <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "GO:BP") %>% 
  dplyr::select(gs_name, gene_symbol)

# Clean up pathway names for the plots
m_t2g$gs_name <- gsub("GOBP_", "", m_t2g$gs_name)
m_t2g$gs_name <- gsub("_", " ", m_t2g$gs_name)

# 4. Run Fast GSEA Algorithm
message(">>> Executing GSEA Algorithm (This might take a minute)...")
gsea_res <- GSEA(geneList = ranked_genes, 
                 TERM2GENE = m_t2g, 
                 minGSSize = 15, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.05, 
                 verbose = FALSE)

# Check if any pathways were actually significant
if (nrow(as.data.frame(gsea_res)) == 0) {
  message(">>> WARNING: No significant GO:BP pathways found for this comparison.")
} else {
  message(">>> Found ", nrow(as.data.frame(gsea_res)), " significant pathways!")
  
  # 5. Calculate Topology for the Network Plot
  gsea_res <- pairwise_termsim(gsea_res)
  
  # ---------------------------------------------------------
  # VISUALIZATION 1: Network Plot (Enrichment Map)
  # ---------------------------------------------------------
  p_network <- emapplot(gsea_res, 
                        showCategory = 40,  
                        color = "NES",      
                        layout = "nicely",
                        node_label = "category") +
    ggtitle(paste(COMPARISON_PREFIX, "- GO:BP Pathway Network"),
            subtitle = paste0("Positive NES = Up in C", NAME_A, " | Negative NES = Up in C", NAME_B))
  
  network_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Network.png")
  ggsave(network_file, plot = p_network, width = 24, height = 20, dpi = PUB_DPI) # Uses Master DPI
  
  # ---------------------------------------------------------
  # VISUALIZATION 2: Classic Faceted Dot Plot
  # ---------------------------------------------------------
  # Map the "activated" (positive NES) and "suppressed" (negative NES) labels dynamically
  custom_labels <- c("activated" = paste0("Up in C", NAME_A), 
                     "suppressed" = paste0("Up in C", NAME_B))
  
  p_dot_wide <- dotplot(gsea_res, 
                        showCategory = 25, 
                        split = ".sign", 
                        label_format = 80, # Wide text so long GO terms fit on one line
                        font.size = 8) + 
    facet_grid(.~.sign, labeller = as_labeller(custom_labels)) +
    ggtitle(paste(COMPARISON_PREFIX, "- Top GO:BP Pathways")) +
    theme(strip.text = element_text(size = 10, face = "bold", color = "black"),
          strip.background = element_rect(fill = "grey90", color = "black"),
          axis.text.y = element_text(size = 8))
  
  dotplot_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_DotPlot.png")
  ggsave(dotplot_file, plot = p_dot_wide, width = 12, height = 10, dpi = PUB_DPI) # Uses Master DPI
  
  # 6. Save raw GSEA results to CSV for your supplementary tables
  csv_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Results.csv")
  write.csv(as.data.frame(gsea_res), csv_file, row.names = FALSE)
  
  message(">>> GSEA outputs saved successfully to ", OUTPUT_DIR)
}