# ==============================================================================
# SCRIPT: 03_Run_GSEA.R
# PURPOSE: Gene Set Enrichment Analysis (GO:BP) + Deep Dive Visualizations
# ==============================================================================
library(Seurat)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)
library(pheatmap) # <-- NEW: Added for Pseudobulk Heatmaps
library(tidyr)

message("\n>>> Running GSEA for: ", COMPARISON_PREFIX)

if(!exists("sobj")) { sobj <- qs_read(INPUT_OBJECT_PATH) }

# 1. Load the Ranked List generated by Script 02
if(!file.exists(DEG_CSV_FILE)) {
  stop(">>> ERROR: Cannot find the DGE CSV. Make sure Script 02 ran successfully!")
}
deg_data <- read.csv(DEG_CSV_FILE)

# 2. Format the Ranked Vector
ranked_genes <- deg_data$avg_log2FC
names(ranked_genes) <- deg_data$gene
ranked_genes <- na.omit(ranked_genes)
ranked_genes <- ranked_genes[!duplicated(names(ranked_genes))]
ranked_genes <- sort(ranked_genes, decreasing = TRUE)

# 3. Fetch GO:BP Pathways
message(">>> Fetching GO:BP database...")
m_t2g <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "GO:BP") %>% 
  dplyr::select(gs_name, gene_symbol)

m_t2g$gs_name <- gsub("GOBP_", "", m_t2g$gs_name)
m_t2g$gs_name <- gsub("_", " ", m_t2g$gs_name)

# 4. Run Fast GSEA Algorithm
message(">>> Executing GSEA Algorithm...")
gsea_res <- GSEA(geneList = ranked_genes, 
                 TERM2GENE = m_t2g, 
                 minGSSize = 15, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.05, 
                 verbose = FALSE)

if (nrow(as.data.frame(gsea_res)) == 0) {
  stop(">>> WARNING: No significant GO:BP pathways found. Stopping GSEA plotting.")
}

message(">>> Found ", nrow(as.data.frame(gsea_res)), " significant pathways!")

# ---------------------------------------------------------
# VISUALIZATION 1 & 2: Network Plot and Dot Plots
# ---------------------------------------------------------
gsea_sim <- pairwise_termsim(gsea_res)

p_network <- emapplot(gsea_sim, showCategory = 40, color = "NES", layout = "fr") +
  ggtitle(paste(COMPARISON_PREFIX, "- GO:BP Pathway Network"))
ggsave(paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Network.png"), plot = p_network, width = 16, height = 14, dpi = PUB_DPI)

gsea_res_A <- gsea_res; gsea_res_A@result <- gsea_res_A@result %>% filter(NES > 0)
gsea_res_B <- gsea_res; gsea_res_B@result <- gsea_res_B@result %>% filter(NES < 0)

if(nrow(gsea_res_A@result) > 0) {
  p_dot_A <- dotplot(gsea_res_A, showCategory = 20, label_format = 80) + ggtitle(paste("Enriched in C", NAME_A))
  ggsave(paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_DotPlot_C", NAME_A, ".png"), plot = p_dot_A, width = 10, height = 8)
}
if(nrow(gsea_res_B@result) > 0) {
  p_dot_B <- dotplot(gsea_res_B, showCategory = 20, label_format = 80) + ggtitle(paste("Enriched in C", NAME_B))
  ggsave(paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_DotPlot_C", NAME_B, ".png"), plot = p_dot_B, width = 10, height = 8)
}

# Save raw results
write.csv(as.data.frame(gsea_res), paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Results.csv"), row.names = FALSE)

# ==============================================================================
# VISUALIZATION 3: DEEP DIVE INTO TOP PATHWAYS (UMAP, Volcano, Heatmap)
# ==============================================================================
message("\n>>> Extracting Top Pathways for Deep Dive Analysis...")

# Select Top 3 pathways for Group A and Top 3 for Group B
top_A_paths <- gsea_res_A@result %>% arrange(desc(NES)) %>% head(3) %>% pull(ID)
top_B_paths <- gsea_res_B@result %>% arrange(NES) %>% head(3) %>% pull(ID)
deep_dive_pathways <- c(top_A_paths, top_B_paths)

if(length(deep_dive_pathways) > 0) {
  
  # --- SMART SUBSETTING FOR HEATMAPS ---
  group_A_label <- paste0("C", NAME_A)
  group_B_label <- ifelse("Rest" %in% CLUSTER_B, "Rest", paste0("C", NAME_B))
  
  if ("Rest" %in% CLUSTER_B) {
    sobj_sub <- sobj
    sobj_sub$Target_Group <- group_B_label
    sobj_sub$Target_Group[sobj_sub$seurat_clusters %in% CLUSTER_A] <- group_A_label
  } else {
    sobj_sub <- subset(sobj, seurat_clusters %in% c(CLUSTER_A, CLUSTER_B))
    sobj_sub$Target_Group <- "Unknown"
    sobj_sub$Target_Group[sobj_sub$seurat_clusters %in% CLUSTER_A] <- group_A_label
    sobj_sub$Target_Group[sobj_sub$seurat_clusters %in% CLUSTER_B] <- group_B_label
  }
  
  Idents(sobj_sub) <- factor(sobj_sub$Target_Group, levels = c(group_A_label, group_B_label))
  
  # Set up tracking for UMAP scores
  pathway_score_names <- c()
  
  # Loop through each of the Top Pathways
  for(pathway in deep_dive_pathways) {
    
    clean_path_name <- substr(gsub("[^A-Za-z0-9]", "_", pathway), 1, 40)
    message("   -> Processing: ", pathway)
    
    # 1. Extract the specific genes driving this pathway from the GSEA result
    core_genes_str <- gsea_res@result[gsea_res@result$ID == pathway, "core_enrichment"]
    pathway_genes <- unlist(strsplit(core_genes_str, "/"))
    valid_genes <- intersect(pathway_genes, rownames(sobj))
    
    if(length(valid_genes) < 2) next # Skip if genes are missing
    
    # ---------------------------------------------------------
    # A: UMAP MODULE SCORE PREP
    # ---------------------------------------------------------
    sobj <- AddModuleScore(sobj, features = list(valid_genes), name = clean_path_name)
    actual_col_name <- paste0(clean_path_name, "1")
    pathway_score_names <- c(pathway_score_names, actual_col_name)
    
    # ---------------------------------------------------------
    # B: PATHWAY-SPECIFIC VOLCANO PLOT
    # ---------------------------------------------------------
    path_deg <- deg_data %>% filter(gene %in% valid_genes)
    
    path_deg$Significance <- "Not Significant"
    path_deg$Significance[path_deg$avg_log2FC > 0.25 & path_deg$p_val_adj < 0.05] <- paste("Up in", group_A_label)
    path_deg$Significance[path_deg$avg_log2FC < -0.25 & path_deg$p_val_adj < 0.05] <- paste("Up in", group_B_label)
    
    top_label <- path_deg %>% filter(Significance != "Not Significant") %>% top_n(15, wt = abs(avg_log2FC)) %>% pull(gene)
    path_deg$Label <- ifelse(path_deg$gene %in% top_label, path_deg$gene, NA)
    
    color_map <- setNames(c("grey85", HEATMAP_HIGH, HEATMAP_LOW), 
                          c("Not Significant", paste("Up in", group_A_label), paste("Up in", group_B_label)))
    
    p_volc <- ggplot(path_deg, aes(x = avg_log2FC, y = -log10(p_val_adj), color = Significance)) +
      geom_point(alpha = 0.8, size = 2) + 
      scale_color_manual(values = color_map) +
      geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed", color = "black") +
      geom_text_repel(aes(label = Label), size = 3, fontface = "bold", color = "black", max.overlaps = 20, na.rm = TRUE) +
      theme_minimal() +
      labs(title = paste("Pathway Drivers:", pathway), subtitle = paste(group_A_label, "vs", group_B_label)) +
      theme(legend.position = "bottom", legend.title = element_blank())
    
    ggsave(paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Volcano_", clean_path_name, ".png"), plot = p_volc, width = 8, height = 6)
    
    # ---------------------------------------------------------
    # C: PATIENT-LEVEL (PSEUDOBULK) HEATMAP
    # ---------------------------------------------------------
    expr_data <- FetchData(sobj_sub, vars = c(valid_genes, "Final_Combined_ID", "Target_Group"))
    
    patient_avg <- expr_data %>%
      group_by(Target_Group, Final_Combined_ID) %>%
      summarise(across(everything(), mean), .groups = "drop") %>%
      mutate(Sample_ID = paste0(Final_Combined_ID, " (", Target_Group, ")"))
    
    annot_df <- data.frame(Cluster = patient_avg$Target_Group)
    rownames(annot_df) <- patient_avg$Sample_ID
    
    annot_colors <- list(Cluster = setNames(c(HEATMAP_HIGH, HEATMAP_LOW), c(group_A_label, group_B_label)))
    
    heat_mat <- patient_avg %>%
      select(-Target_Group, -Final_Combined_ID) %>%
      tibble::column_to_rownames("Sample_ID") %>%
      as.matrix() %>%
      t()
    
    heat_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Heatmap_", clean_path_name, ".png")
    
    # --- THE FIX: Taller rows and a much larger canvas ---
    # We allocate exactly 15 pixels per gene, plus 300 extra pixels for the titles/margins
    plot_height <- max(600, (length(valid_genes) * 15) + 400)
    
    png(heat_file, width = 800, height = plot_height, res = 300)
    pheatmap(heat_mat,
             scale = "row",
             annotation_col = annot_df,
             annotation_colors = annot_colors,
             color = colorRampPalette(c("navy", "white", "firebrick3"))(100),
             cluster_cols = TRUE, 
             cluster_rows = TRUE, 
             show_colnames = TRUE,
             cellheight = 12,        # Forces every single row to be exactly 12 pixels tall
             fontsize_row = 10,      # Makes the gene names perfectly legible
             main = paste("Patient-Level Heatmap:", pathway))
    dev.off()
  }
  
  # ---------------------------------------------------------
  # D: THE GLOBAL GSEA UMAP GRID
  # ---------------------------------------------------------
  message(">>> Plotting GSEA UMAP Overlays...")
  if(length(pathway_score_names) > 0) {
    p_umap <- FeaturePlot(sobj, features = pathway_score_names, ncol = 3, pt.size = 0.5) &
      scale_color_gradientn(colors = c("navy", "grey90", "firebrick3"), name = "Score") &
      theme(plot.title = element_text(size = 9, face = "bold"))
    
    ggsave(paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_UMAP_Scores.png"), plot = p_umap, width = 15, height = 10, dpi = PUB_DPI)
  }
}

message(">>> GSEA Deep Dive Analysis complete! Check ", OUTPUT_DIR, " for UMAPs, Volcanos, and Heatmaps.")