# ==============================================================================
# SCRIPT: 03_Run_GSEA.R
# PURPOSE: Gene Set Enrichment Analysis (GO:BP) and Split Network Visualization
# ==============================================================================
library(dplyr)
library(ggplot2)
library(msigdbr)
library(clusterProfiler)
library(enrichplot)

message("\n>>> Running GSEA for: ", COMPARISON_PREFIX)

# 1. Load the Ranked List generated by Script 02
if(!file.exists(DEG_CSV_FILE)) {
  stop(">>> ERROR: Cannot find the DGE CSV. Make sure Script 02 ran successfully!")
}
deg_data <- read.csv(DEG_CSV_FILE)

# 2. Format the Ranked Vector strictly for clusterProfiler
ranked_genes <- deg_data$avg_log2FC
names(ranked_genes) <- deg_data$gene
ranked_genes <- na.omit(ranked_genes)
ranked_genes <- ranked_genes[!duplicated(names(ranked_genes))]
ranked_genes <- sort(ranked_genes, decreasing = TRUE)

# 3. Fetch GO:BP Pathways
message(">>> Fetching GO:BP database...")
m_t2g <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "GO:BP") %>% 
  dplyr::select(gs_name, gene_symbol)

# Clean up pathway names for the plots
m_t2g$gs_name <- gsub("GOBP_", "", m_t2g$gs_name)
m_t2g$gs_name <- gsub("_", " ", m_t2g$gs_name)

# 4. Run Fast GSEA Algorithm
message(">>> Executing GSEA Algorithm (This might take a minute)...")
gsea_res <- GSEA(geneList = ranked_genes, 
                 TERM2GENE = m_t2g, 
                 minGSSize = 15, 
                 maxGSSize = 500, 
                 pvalueCutoff = 0.05, 
                 verbose = FALSE)

# Check if any pathways were actually significant
if (nrow(as.data.frame(gsea_res)) == 0) {
  message(">>> WARNING: No significant GO:BP pathways found for this comparison.")
} else {
  message(">>> Found ", nrow(as.data.frame(gsea_res)), " significant pathways!")
  
  # 5. Calculate Topology for the Network Plot
  gsea_res <- pairwise_termsim(gsea_res)
  
  # ---------------------------------------------------------
  # VISUALIZATION 1: Network Plot (Enrichment Map) - Condensed
  # ---------------------------------------------------------
  p_network <- emapplot(gsea_res, 
                        showCategory = 40,  
                        color = "NES",      
                        layout = "fr",      
                        node_label = "category") +
    ggtitle(paste(COMPARISON_PREFIX, "- GO:BP Pathway Network"),
            subtitle = paste0("Positive NES = Up in C", NAME_A, " | Negative NES = Up in C", NAME_B)) +
    theme(plot.title = element_text(face = "bold", size = 16))
  
  # --- FIX 3: Shrink the canvas footprint to naturally eliminate white space ---
  network_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Network.png")
  ggsave(network_file, plot = p_network, width = 16, height = 14, dpi = PUB_DPI)
  
  # ---------------------------------------------------------
  # VISUALIZATION 2: Split Dot Plots (One for each group)
  # ---------------------------------------------------------
  # Create two separate GSEA result objects by filtering the NES direction
  gsea_res_A <- gsea_res
  gsea_res_A@result <- gsea_res@result %>% filter(NES > 0)
  
  gsea_res_B <- gsea_res
  gsea_res_B@result <- gsea_res@result %>% filter(NES < 0)
  
  # --- Plot for Group A (Positive NES) ---
  if(nrow(gsea_res_A@result) > 0) {
    p_dot_A <- dotplot(gsea_res_A, showCategory = 20, label_format = 80, font.size = 10) + 
      ggtitle(paste("Pathways Enriched in C", NAME_A), subtitle = paste("Compared to C", NAME_B)) +
      theme(axis.text.y = element_text(size = 9),
            plot.title = element_text(face = "bold"))
    
    file_A <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_DotPlot_C", NAME_A, ".png")
    ggsave(file_A, plot = p_dot_A, width = 10, height = 8, dpi = PUB_DPI)
  } else {
    message(">>> No positive NES pathways found for C", NAME_A)
  }
  
  # --- Plot for Group B (Negative NES) ---
  if(nrow(gsea_res_B@result) > 0) {
    p_dot_B <- dotplot(gsea_res_B, showCategory = 20, label_format = 80, font.size = 10) + 
      ggtitle(paste("Pathways Enriched in C", NAME_B), subtitle = paste("Compared to C", NAME_A)) +
      theme(axis.text.y = element_text(size = 9),
            plot.title = element_text(face = "bold"))
    
    file_B <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_DotPlot_C", NAME_B, ".png")
    ggsave(file_B, plot = p_dot_B, width = 10, height = 8, dpi = PUB_DPI)
  } else {
    message(">>> No negative NES pathways found for C", NAME_B)
  }
  
  # 6. Save raw GSEA results to CSV for your supplementary tables
  csv_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Results.csv")
  write.csv(as.data.frame(gsea_res), csv_file, row.names = FALSE)
  # ---------------------------------------------------------
  # VISUALIZATION 3: Classic Broad Institute GSEA Plots
  # ---------------------------------------------------------
  message(">>> Generating Classic Broad-Style GSEA Plots for Top 5 Pathways...")
  
  # Helper function to plot and save the top N pathways
  plot_top_gsea <- function(full_gsea, subset_res, group_name, top_n = 5) {
    
    # Sort the subset to get the absolute strongest drivers (by absolute NES)
    top_pathways <- subset_res@result %>% 
      arrange(desc(abs(NES))) %>% 
      head(top_n)
    
    if(nrow(top_pathways) == 0) return(NULL)
    
    for(i in 1:nrow(top_pathways)) {
      pathway_id <- top_pathways$ID[i]
      pathway_name <- top_pathways$Description[i]
      
      # Clean the pathway name so it doesn't break the file system
      clean_name <- gsub("[^A-Za-z0-9]", "_", pathway_name)
      clean_name <- substr(clean_name, 1, 50) # Cap length
      
      # Generate the classic Broad-style plot
      p_classic <- gseaplot2(full_gsea, 
                             geneSetID = pathway_id, 
                             title = pathway_name, 
                             pvalue_table = TRUE) # Adds the exact p-value/NES table inside the plot!
      
      file_name <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_ClassicGSEA_C", group_name, "_", clean_name, ".png")
      ggsave(file_name, plot = p_classic, width = 12, height = 6, dpi = PUB_DPI)
    }
  }
  
  # Run the function for both sides
  plot_top_gsea(gsea_res, gsea_res_A, NAME_A, top_n = 5)
  plot_top_gsea(gsea_res, gsea_res_B, NAME_B, top_n = 5)
  
  # 6. Save raw GSEA results to CSV for your supplementary tables
  csv_file <- paste0(OUTPUT_DIR, COMPARISON_PREFIX, "_GSEA_Results.csv")
  write.csv(as.data.frame(gsea_res), csv_file, row.names = FALSE)
  
  message(">>> GSEA outputs saved successfully to ", OUTPUT_DIR)
}


